version: "3.8"

services:
  server:
    build:
      context: .
    container_name: annotator-tool
    ports:
      - "8000:${SERVER_PORT}"
    networks:
      - app-network
    environment:
      - SERVER_PORT=$SERVER_PORT

networks:
  app-network:
    driver: bridge
